# Generated by Django 4.2.15 on 2024-09-17 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="restaurant",
            new_name="restaurants",
        ),
    ]
