# Generated by Django 4.2.15 on 2024-09-12 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_order_options_courier_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="restaurant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.restaurant",
            ),
        ),
    ]
