# Generated by Django 4.2.15 on 2024-09-17 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_rename_restaurant_cart_restaurants"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="restaurants",
            new_name="restaurant",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="cart_items",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="cart_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.cartitem",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.dish"
            ),
        ),
    ]
