# Generated by Django 4.2.15 on 2024-09-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_rename_restaurants_cart_restaurant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="cart_item",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="quantity",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="cart_items",
            field=models.ManyToManyField(
                related_name="order_items", to="store.cartitem"
            ),
        ),
    ]
