# Generated by Django 4.2.15 on 2024-09-12 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_restaurant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.restaurant"
            ),
        ),
    ]
