# Generated by Django 4.2.15 on 2024-09-18 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_remove_orderitem_cart_item_remove_orderitem_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="cart_items",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="cart_item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.cartitem",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="courier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.courier",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_fee",
            field=models.DecimalField(decimal_places=2, default=950, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
