# Generated by Django 4.2.15 on 2024-09-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_remove_product_restaurant_product_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courier",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("suspended", "Suspended"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
