# Generated by Django 4.2.15 on 2024-09-12 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="teacher",
        ),
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
