# Generated by Django 4.2.15 on 2024-09-17 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0001_initial"),
        ("user", "0002_alter_profile_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="restaurant",
        ),
        migrations.AddField(
            model_name="profile",
            name="restaurants",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
