# Generated by Django 4.2.15 on 2024-09-15 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_product_restaurant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0002_remove_profile_teacher_delete_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="restaurant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
